org: kenshotakizawa
app: line-chatbot-api
service: line-chatbot-api

provider:
  name: aws
  stage: stg
  region: ap-northeast-1
  runtime: nodejs20.x
  apiGateway:
    shouldStartNameWithService: true

functions:
  addExp:
    handler: src/functions/addExp/index.handler
    events:
      - httpApi:
          path: /users/{lineUserId}/addExp
          method: post

  getUserRelationLevel:
    handler: src/functions/getUserRelationLevel/index.handler
    events:
      - httpApi:
          path: /users/{lineUserId}/relation-level/ais/{aiId}
          method: get

  getUserSubscription:
    handler: src/functions/getUserSubscription/index.handler
    events:
      - httpApi:
          path: users/{lineUserId}/subscriptions/ais/{aiId}
          method: get

  createUserSubscription:
    handler: src/functions/createUserSubscription/index.handler
    events:
      - httpApi:
          path: users/{lineUserId}/subscriptions
          method: post

  getDailyConversationCount:
    handler: src/functions/getDailyConversationCount/index.handler
    events:
      - httpApi:
          path: users/{lineUserId}/dailyConversationCount/ais/{aiId}
          method: get

  incrementDailyConversationCount:
    handler: src/functions/incrementDailyConversationCount/index.handler
    events:
      - httpApi:
          path: users/{lineUserId}/ais/{aiId}/dailyConversationCount
          method: put

  canUserConverse:
    handler: src/functions/canUserConverse/index.handler
    events:
      - httpApi:
          path: users/{lineUserId}/canUserConverse/ais/{aiId}/
          method: get

plugins:
  - serverless-offline
  - serverless-dotenv-plugin